name: Download v2rayN, v2rayNG, nekoray, and NekoBox Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download files
        run: |
          set -e

          # Define an array of repositories and their corresponding download patterns
          declare -A repos=(
            ["v2rayN"]="https://api.github.com/repos/2dust/v2rayN/releases/latest v2rayN-windows-64-With-Core.zip"
            ["v2rayNG"]="https://api.github.com/repos/2dust/v2rayNG/releases/latest arm64-v8a v2rayNG.apk"
            ["nekoray"]="https://api.github.com/repos/MatsuriDayo/nekoray/releases/latest windows nekoray.zip"
            ["NekoBox"]="https://api.github.com/repos/MatsuriDayo/NekoBoxForAndroid/releases/latest arm64-v8a NekoBox.apk"
          )

          for repo in "${!repos[@]}"; do
            IFS=' ' read -r url pattern output <<< "${repos[$repo]}"
            echo "开始下载 $repo 文件..."
            response=$(curl -s "$url")
            download_url=$(echo "$response" | jq -r ".assets[] | select(.name | contains(\"$pattern\")) | .browser_download_url")

            if [ -n "$download_url" ]; then
              echo "找到下载链接: $download_url"
              curl -L -o "$output" "$download_url"
              echo "$output 下载完成！"
            else
              echo "未找到符合条件的文件: $pattern"
            fi
          done

      - name: Check downloaded files
        run: |
          echo "检查下载的文件..."
          for file in v2rayN-windows-64-With-Core.zip v2rayNG.apk nekoray.zip NekoBox.apk; do
            if [ -e "$file" ]; then
              echo "$file 存在。"
            else
              echo "$file 不存在！"
            fi
          done

      - name: Commit 和 push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2rayN-windows-64-With-Core.zip v2rayNG.apk nekoray.zip NekoBox.apk
          git commit -m "Add latest files" --allow-empty || echo "没有文件可以提交。"
          git push
