name: Download v2rayN, v2rayNG, nekoray, and NekoBox Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download files
        run: |
          set -e

          # 定义下载函数
          download_file() {
              local repo_url=$1
              local asset_name=$2
              local output_name=$3

              echo "从 $repo_url 获取最新版本信息..."
              local response=$(curl -s "$repo_url/releases/latest")
              local download_url=$(echo "$response" | jq -r ".assets[] | select(.name | contains(\"$asset_name\")) | .browser_download_url")

              if [ -n "$download_url" ]; then
                  echo "找到下载链接: $download_url"
                  echo "正在下载: $output_name..."
                  curl -L -o "$output_name" "$download_url"
                  echo "$output_name 下载完成！"
              else
                  echo "未找到包含 '$asset_name' 的文件"
              fi
          }

          # 下载文件
          download_file "https://github.com/2dust/v2rayN" "v2rayN-windows-64-With-Core.zip" "v2rayN.zip"
          download_file "https://github.com/2dust/v2rayNG" "_arm64-v8a.apk" "v2rayNG.apk"
          download_file "https://github.com/MatsuriDayo/nekoray" "windows" "nekoray.zip"
          download_file "https://github.com/MatsuriDayo/NekoBoxForAndroid" "arm64-v8a" "NekoBox.apk"

      - name: Check downloaded files
        run: |
          for file in v2rayN.zip v2rayNG.apk nekoray.zip NekoBox.apk; do
              if [ -e "$file" ]; then
                  echo "$file 存在。"
              else
                  echo "$file 不存在！"
              fi
          done

      - name: Commit 和 push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2rayN.zip v2rayNG.apk nekoray.zip NekoBox.apk
          git commit -m "Add latest files" --allow-empty || echo "没有文件可以提交。"
          git push
