name: Download v2rayN File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download file
        run: |
          #!/bin/bash
          set -e

          echo "开始下载最新的 v2rayN 文件..."

          # GitHub API URL
          url="https://api.github.com/repos/2dust/v2rayN/releases/latest"
          echo "获取最新版本信息..."

          # 获取最新版本信息
          response=$(curl -s "$url")
          echo "成功获取版本信息。"

          # 只下载第一个文件
          file_name="v2rayN-windows-64-With-Core.zip"
          echo "正在查找下载链接: $file_name"
          download_url=$(echo "$response" | jq -r ".assets[] | select(.name == \"$file_name\") | .browser_download_url")

          if [ -n "$download_url" ]; then
              echo "找到下载链接: $download_url"
              echo "正在下载: $file_name..."
              curl -L -o "$file_name" "$download_url"
              echo "$file_name 下载完成！"
          else
              echo "未找到文件: $file_name"
          fi

      - name: Check downloaded file
        run: |
          echo "检查下载的文件..."
          if [ -e "v2rayN-windows-64-With-Core.zip" ]; then
              echo "v2rayN-windows-64-With-Core.zip 存在。"
          else
              echo "v2rayN-windows-64-With-Core.zip 不存在！"
          fi

      - name: Commit 和 push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add v2rayN-windows-64-With-Core.zip
          git commit -m "Add latest v2rayN file" --allow-empty || echo "没有文件可以提交。"
          git push
