name: Download Latest v2rayN Release

on:
  push:
    branches:
      - main  # 或者你想要触发的其他分支
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 使用最新的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Download v2rayN-windows-64-With-Core.zip
        run: |
          import requests

          # GitHub API URL
          url = "https://api.github.com/repos/2dust/v2rayN/releases/latest"

          # 获取最新版本信息
          response = requests.get(url)
          data = response.json()

          # 查找特定的下载链接
          download_url = next(
              (asset['browser_download_url'] for asset in data['assets'] 
               if asset['name'] == 'v2rayN-windows-64-With-Core.zip'), 
              None
          )

          if download_url:
              print(f"正在下载: {download_url}")
              with requests.get(download_url, stream=True) as r:
                  r.raise_for_status()  # 检查请求是否成功
                  with open('v2rayN-windows-64-With-Core.zip', 'wb') as f:
                      for chunk in r.iter_content(chunk_size=8192):
                          f.write(chunk)
              print("下载完成！")
          else:
              print("未找到指定的文件！")

      - name: Commit and Push
        run: |
          git config --local user.email "you@example.com"  # 替换为你的邮箱
          git config --local user.name "Your Name"  # 替换为你的名字
          git add v2rayN-windows-64-With-Core.zip
          git commit -m "Add v2rayN-windows-64-With-Core.zip"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
