name: Download Multiple v2rayN Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download files
        run: |
          #!/bin/bash
          set -e

          echo "开始下载最新的 v2rayN 文件..."

          # GitHub API URL
          url="https://api.github.com/repos/2dust/v2rayN/releases/latest"
          echo "获取最新版本信息..."

          # 获取最新版本信息
          response=$(curl -s "$url")
          echo "成功获取版本信息。"

          # 要下载的文件名列表
          files_to_download=(
              "v2rayN-windows-64-With-Core.zip"
              "v2rayN-windows-64.zip"
              "v2rayN-windows-64-Installer.zip"
          )

          for file_name in "${files_to_download[@]}"; do
              echo "正在查找下载链接: $file_name"
              download_url=$(echo "$response" | jq -r ".assets[] | select(.name == \"$file_name\") | .browser_download_url")

              if [ -n "$download_url" ]; then
                  echo "找到下载链接: $download_url"
                  echo "正在下载: $file_name..."
                  curl -L -o "$file_name" "$download_url"
                  echo "$file_name 下载完成！"
              else
                  echo "未找到文件: $file_name"
              fi
          done

      - name: Commit and Push
        run: |
          echo "准备提交下载的文件..."
          git config --local user.email "you@example.com"  # 替换为你的邮箱
          git config --local user.name "Your Name"  # 替换为你的名字
          git add v2rayN-windows-64-With-Core.zip v2rayN-windows-64.zip v2rayN-windows-64-Installer.zip
          git commit -m "Add latest v2rayN files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
